In [1]:
from itertools import permutations
from math import factorial
import numpy as np

N is the total number of different possible positions. e.g. 32*7=224 for long PT

n is the number of elements. e.g. 60 in 1868

### No. unique configurations not keeping order:

\begin{equation}
\frac{N!}{(N-n)!}
\end{equation}

### No. configurations keeping order but not unique:

\begin{equation}
\frac{N!}{n!}
\end{equation}

### No. unique configurations and keeping order:

\begin{equation}
\frac{N!}{(N-n)!n!}
\end{equation}

In [3]:
N = 9     # Numero de posiciones (32*7 para PT)
n = 4     # Numero de elementos (1,2,3,4,...)

zeros = [0]*(N-n) 
unique_elems = [i for i in range(1,n+1)]

perms = np.array(list(permutations(zeros + unique_elems)))

# Según formula, es:

print("No. unique configurations not keeping order:\t",int(factorial(N)/(factorial(N-n))))

print("No. configurations keeping order but not unique:",int(factorial(N)/(factorial(n))))

print("No. unique configurations and keeping order:\t",int(factorial(N)/(factorial(N-n)*factorial(n))))

No. unique configurations not keeping order:	 3024
No. configurations keeping order but not unique: 15120
No. unique configurations and keeping order:	 126


In [4]:
#No. unique configurations not keeping order
a = np.unique(perms,axis=0)   # Take only unique permutations (that is, make all zeros equal)
a.shape[0]

3024

In [5]:
condition = True
for i in unique_elems[:-1]:
    tmp_i = (perms == i).nonzero()[1]  # Get index of element i in permutation
    tmp_i_1 = (perms == i+1).nonzero()[1]  # Get index of element i+1 in permutation
    
    condition = condition & (tmp_i < tmp_i_1)
    
#No. configurations keeping order but not unique
a = perms[condition]
a.shape[0]

15120

In [13]:
uniqs = np.unique(a,axis=0)
uniqs.shape[0]

126

In [14]:
import sys
np.set_printoptions(threshold=sys.maxsize)

uniqs[0:30]

array([[0, 0, 0, 0, 0, 1, 2, 3, 4],
       [0, 0, 0, 0, 1, 0, 2, 3, 4],
       [0, 0, 0, 0, 1, 2, 0, 3, 4],
       [0, 0, 0, 0, 1, 2, 3, 0, 4],
       [0, 0, 0, 0, 1, 2, 3, 4, 0],
       [0, 0, 0, 1, 0, 0, 2, 3, 4],
       [0, 0, 0, 1, 0, 2, 0, 3, 4],
       [0, 0, 0, 1, 0, 2, 3, 0, 4],
       [0, 0, 0, 1, 0, 2, 3, 4, 0],
       [0, 0, 0, 1, 2, 0, 0, 3, 4],
       [0, 0, 0, 1, 2, 0, 3, 0, 4],
       [0, 0, 0, 1, 2, 0, 3, 4, 0],
       [0, 0, 0, 1, 2, 3, 0, 0, 4],
       [0, 0, 0, 1, 2, 3, 0, 4, 0],
       [0, 0, 0, 1, 2, 3, 4, 0, 0],
       [0, 0, 1, 0, 0, 0, 2, 3, 4],
       [0, 0, 1, 0, 0, 2, 0, 3, 4],
       [0, 0, 1, 0, 0, 2, 3, 0, 4],
       [0, 0, 1, 0, 0, 2, 3, 4, 0],
       [0, 0, 1, 0, 2, 0, 0, 3, 4],
       [0, 0, 1, 0, 2, 0, 3, 0, 4],
       [0, 0, 1, 0, 2, 0, 3, 4, 0],
       [0, 0, 1, 0, 2, 3, 0, 0, 4],
       [0, 0, 1, 0, 2, 3, 0, 4, 0],
       [0, 0, 1, 0, 2, 3, 4, 0, 0],
       [0, 0, 1, 2, 0, 0, 0, 3, 4],
       [0, 0, 1, 2, 0, 0, 3, 0, 4],
       [0, 0, 1, 2, 0, 0, 3,

In [18]:
i=100

print(uniqs[i])
print()
print(uniqs[i].reshape(3,3))

[1 0 2 3 0 0 0 0 4]

[[1 0 2]
 [3 0 0]
 [0 0 4]]


## That said, how many different possible PTs exist where the order is preserved?

In [32]:
N = 30*7     # Numero de posiciones (32*7)
n = 60     # Numero de elementos (1,2,3,4,...)

print("No. unique configurations not keeping order:\t",factorial(N)/(factorial(N-n)))

#print("No. configurations keeping order but not unique:",factorial(N)//(factorial(n)))

print("No. unique configurations and keeping order:\t",factorial(N)/(factorial(N-n)*factorial(n)))

print(f"\nDifference is a factor of:\t\t\t {factorial(n):.15e}")

No. unique configurations not keeping order:	 1.8522056472827472e+135
No. unique configurations and keeping order:	 2.225944617131523e+53

Difference is a factor of:			 8.320987112741390e+81
